version: '3.9'
services:
  app:
    build: .
    container_name: app1
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./db:/db